#!/bin/sh
internetoff="[KO]"
network_name=`nm-tool 2> /dev/null | grep "*" | tail -1 | cut -d: -f1 | sed -e 's/ //g' -e 's/*//'`

curl --max-time 2 -s http://whatismyip.akamai.com/ > /dev/null &&\
  echo "#[fg=blue]$network_name#[default]" ||\
  echo "#[fg=red]$internetoff#[default]"

