#!/bin/sh
internetoff="[KO]"
if [ `uname` = "Linux" ]; then
  network_name=`nm-tool 2> /dev/null | grep "*" | tail -1 | cut -d: -f1 | sed -e 's/ //g' -e 's/*//'`
else
  network_name=`airport -I | grep "[^B]SSID" | cut -d':' -f 2 | cut -d' ' -f 2-`
fi

curl --max-time 2 -s http://whatismyip.akamai.com/ > /dev/null &&\
  echo "#[fg=blue]$network_name#[default]" ||\
  echo "#[fg=red]$internetoff#[default]"

