#!/bin/sh

LOADS=`uptime | cut -d "," -f 3- | cut -d ":" -f2 | sed -e "s/^[ \t]*//" -e "s/,/./g" -e "s/. / /g"`

LOAD1=`echo $LOADS | cut -d " " -f 1`
LOAD2=`echo $LOADS | cut -d " " -f 2`
LOAD3=`echo $LOADS | cut -d " " -f 3`

LOAD1TMP=`echo $LOAD1*10 | bc -q | cut -d "." -f 1` 
LOAD2TMP=`echo $LOAD2*10 | bc -q | cut -d "." -f 1` 
LOAD3TMP=`echo $LOAD3*10 | bc -q | cut -d "." -f 1` 

if [ $LOAD1TMP -ge 15 ]; then
  COLOR1="#[fg=red]"
elif [ $LOAD1TMP -ge 10 ] && [ $LOAD1TMP -lt 15 ]; then
  COLOR1="#[fg=yellow]"
else
  COLOR1="#[fg=green]"
fi

if [ $LOAD2TMP -ge 9 ]; then
  COLOR2="#[fg=red]"
elif [ $LOAD2TMP -ge 5 ] && [ $LOAD2TMP -lt 9 ]; then
  COLOR2="#[fg=yellow]"
else
  COLOR2="#[fg=green]"
fi

if [ $LOAD3TMP -ge 9 ]; then
  COLOR3="#[fg=red]"
elif [ $LOAD3TMP -ge 5 ] && [ $LOAD3TMP -lt 9 ]; then
  COLOR3="#[fg=yellow]"
else
  COLOR3="#[fg=green]"
fi
echo "$COLOR1$LOAD1 $COLOR2$LOAD2 $COLOR3$LOAD3#[default]"
