#!/bin/sh

if [ `uname` = "Linux" ]; then
  number=$(ps aux | grep banshee | grep -v "grep\|tmux" | wc -l)

  if [ $number -gt 0 ]; then
    state=$(/usr/bin/banshee --query-current-state | cut -d' ' -f 2-)

    if [ $state = "playing" ]; then
      artist=$(/usr/bin/banshee --query-artist | cut -d' ' -f 2-)
      title=$(/usr/bin/banshee --query-title | cut -d' ' -f 2-)
      info="$artist - $title"
    else
      info=$(. ~/.dotfiles/tmux/scripts/lastfm.sh)
    fi
  else
    info=$(. ~/.dotfiles/tmux/scripts/lastfm.sh)
  fi
else [ `uname` = "Darwin" ];
  number=$(ps aux | grep "iTunes " | grep -v "grep\|tmux" | wc -l)
  if [ $number -gt 0 ]; then
    info=$(osascript ~/.dotfiles/tmux/scripts/itunes.script)
  else
    info=$(. ~/.dotfiles/tmux/scripts/lastfm.sh)
  fi
fi
[[ $info ]] && echo "$info ❮ "
