# Inserts a blank line between shell prompts
add_newline = false

format = '''$hostname($directory )([\[$git_branch$git_commit$git_status\]](bold blue))(${custom.git_wip})( $cmd_duration)
$jobs$character
'''

[hostname]
ssh_only = true
format = '[$hostname: ](bold red)'
disabled = false

[directory]
format = '$path'

[git_branch]
format = '[$branch](bold blue)'
only_attached = true
disabled = false

[git_commit]
format = '$hash'
only_detached = true
disabled = false

[git_status]
stashed = '\$'
modified = '#'
untracked = '+'
deleted = '-'
format = '$untracked$modified$deleted$stashed'
disabled = false

[cmd_duration]
format = '[$duration](bold green)'

[character]
format = "$symbol "
success_symbol = '[›](bold green)'
error_symbol = '[›](bold red)'

[custom.git_wip]
command = 'echo "[WIP]"'
when = "git log --pretty=format:'%s' -1 2> /dev/null | grep -ic wip"
style = 'bold blue'
format = "[$output]($style)"
disabled = false

# TODO:
# * Display git stuff for sparse-checkouts.
