#!/usr/bin/env bash

  # ctags --tag-relative -L - --languages=ruby
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | ctags -L - -R --languages=ruby --exclude=.git --exclude=log $dir $(bundle list --paths) --tag-relative
