#!/usr/bin/env bash

set -e

PATH="/usr/local/bin:$PATH"
WORKING_DIRECTORY="`git rev-parse --git-dir`"
trap 'rm -f "$WORKING_DIRECTORY/$$.tags"' EXIT

git ls-files | ctags -L - -R --languages=ruby --exclude=.git --exclude=log \
  --exclude=db/migrate $WORKING_DIRECTORY $(bundle list --paths) --tag-relative
