#!/usr/bin/env bash

# Install Homebrew, requires Xcode CLI tools.
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install required formulaes
brew install \
  ack \
  bash \
  git \
  go \
  hg \
  irssi \
  jq \
  mongodb \
  postgresql \
  rbenv \
  reattach-to-user-namespace \
  redis \
  ruby-build \
  selecta \
  tcsh \
  tmux \
  tree \
  vim \
  wget \
  youtube-dl

# Install pow
curl get.pow.cx | sh

# Install heroku toolbelt
open "https://toolbelt.heroku.com/"
