#!/bin/bash

# If not running interactively, don't do anything
if [[ -n "$PS1" ]] ; then

  # Source global definitions.
  [[ -s "/etc/bashrc" ]] && source "/etc/bashrc"

  # Source local shit.
  [[ -s "$HOME/.bashrc.local" ]] && source "$HOME/.bashrc.local"

  # Put secret configuration settings in ~/.secrets
  [[ -s "$HOME/.secrets" ]] && source "$HOME/.secrets"

  if [[ -d /usr/local/etc/bash_completion.d ]]; then
    for comp_file in /usr/local/etc/bash_completion.d/**
    do
      source $comp_file
    done
  fi

  # Source personnal config files.
  for config_file in ~/.dotfiles/**/*.sh
  do
    source $config_file
  done

  # Set teminal as 256 colors.
  if [ -z $TMUX ]; then
    if [ -e /usr/share/terminfo/x/xterm-256color ]; then
      export TERM='xterm-256color'
    else
      export TERM='xterm-color'
    fi
  fi
fi
