#!/bin/bash

# Setup homebrew stuff ASAP.
if [[ -d /opt/homebrew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# shellcheck source=/Users/alioudiallo/.bashrc
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
